name: Scrape and Notify

on:
  schedule:
    - cron: '0 0 * * *'  # JST 9:00
    - cron: '0 4 * * *'  # JST 13:00
    - cron: '0 9 * * *'  # JST 18:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Pythonの環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. スクレイピングスクリプトを実行
      - name: Run scraper
        run: python run.py

      # 5. 【追加したステップ】変更されたファイルをコミット＆プッシュ
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # コミットメッセージ
          commit_message: "chore: Update data files"
          # コミット対象のファイルパターン (data/ ディレクトリ以下の全jsonファイル)
          file_pattern: "data/*.json"